### ISSUE TITLE
Playing space hermit is now impossible because mining asteroid rock makes the tile act as space for a second.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10018]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Be space hermit, mine rock, tile acts like space, freezes and succs all the air around.

**Comment by Ghommie** [comment]
I assume that's because it uses the standard space mining rock turfs, and the atmos adjacency subsystem I ported made the air contents merging not instant but queued.

By the by, on the same wavelength, there issues with many turf changes proc calls not having the inherit air contents flag on, and thus generating new air mixes (example: changing a holodeck). Basically an issue that got fixed on tgstation months ago, which I'd probably port in a couple days at most. Just saying.
