### ISSUE TITLE
Weakened Virus Plasma Mutates Two Symptoms

### ISSUE THREAD

**Issue by IronEleven** [citadel-station/citadel-main#10686]
## Round ID:
21120

## Testmerges:
#10629: 'Putnamos aka "i made LINDA fast"' by Putnam3145 at commit 347f72b1c1
#10414: 'The Great Citadel De-Pissening of 2020' by CameronWoof at commit 0c70fc9234
#10352: 'Changes to the way SM handles power related to integrity and max integrity damage' by Seris02 at commit 2ca4c2e66a
#10572: 'Removes harm prevention clause indicators from relevant sources.' by Tupinambis at commit dd9e62c8bb
#10389: '[TESTMERGE ONLY] dumb hotfix' by Putnam3145 at commit 36bc39aad8
#10581: '[WIP] Taser re-rework: Turns tasers into a right-click action of hybrid tasers, nerfs electrodes similarly to taser kneecapping' by deathride58 at commit b931255abb
#10575: '[TESTMERGE] Properly working TGUI Next' by Arturlang at commit 255f2ce449

## Reproduction:
Mix weakened virus plasma in a beaker using a dropper (1u virus food, 1u plasma, then 1u synaptizine), then add a sample of infected blood.  This will produce two symptoms instead of the expected one.

**Comment by Ghommie** [comment]
That's because the weakened virus plasma reaction produces 2 units:
https://github.com/Citadel-Station-13/Citadel-Station-13/blob/3c53619f2add33f6e99ada3bbec58167007c3de4/code/modules/reagents/chemistry/recipes/others.dm#L183
And Kevinz changed viro so mixing bigger amounts of virus mutagen/food with blood can lead to repeated changes, up to 5u. Make sure to use a dropper.
