### ISSUE TITLE
Feature Request: Easier way to change hair color while in game

### ISSUE THREAD

**Issue by izzyinbox** [citadel-station/citadel-main#10735]
Currently the only way to adjust your hair color is to have genetics roll the dice or revert your DNA to your round-start color, or having it randomly selected by chemical hair dye.
Unlike with full hair style selection in a mirror, this makes it a pain in the ass to fix hair color it gets changed unexpectedly.

This feature would also fix how ban-bait it is to smoke machine/grenade hair dye as a "prank", given the extreme difficulty to fix what is so easily done.
Compared to the "prank" of shaving someone's hair off, which isn't able to be done on a large scale, and is much easier to fix once the prank is over. Hair color should follow suit.

~~inb4 "snowflake"~~

**Comment by Ghommie** [comment]
> hair dye pranks being a ban bait.

Really, no one should be banned because of a repentine uncalled change in hair color, though I do agree there is no easy way to change color hair at the time.
Also i'm about close most if not all feature resquests soon, I'm a bit upset people are using the issues section to make feature requests when those should be done on the discord or forum.
