### ISSUE TITLE
Prescription Not Available

### ISSUE THREAD

**Issue by TripleShades** [citadel-station/citadel-main#11286]
Issue reported from  Round ID: 21762 (Citadel Station 13)

Reporting client version: 513

Combining a regular Prescription HUD of either medical or security kind with sunglasses to make a Sunglasses HUD removes the prescription, leaving you without usable eyewear.

**Comment by Ragolution** [comment]
~~That honestly seems like not-a-bug. Bug report is unclear. Prescription sunglasses aren't really a thing, unless you're going to code in transitional lenses, which could be neat, but defeats one of the reasons why prescription glasses are a drawback.~~

~~To clarify; Does the crafting recipe destroy the prescription HUD used in the recipe and **fail** or does it just make a HUD without the prescription quality?~~

Not a bug, but a dumb feature. I'll work on a PR to fix this in an amenable way.
If you want to 'steal' my code, you're fully free, it should be here:

https://github.com/Ragolution/Citadel-Station-13/tree/Hudscription

It's completely working and compiles. The only problem is right now I can't post the PR because I merged my audio file edit into my master like a dummy. If you want to make the PR for yourself, all you need to do copy the update to "/code/datums/components/crafting/recipes/recipes_clothing.dm" file from my branch to Citadel's main.
