### ISSUE TITLE
Lighteater Doing Little Damage to Objects

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#12245]
## Round ID:
ID 22907

## Testmerges:
#12075: 'Field of Vision component.' by Ghommie at commit 226d0f111f
#12175: 'Adds a New map, Snow Taxi (A vgstation13 map port)' by Detective-Google at commit 4378a34ea7
#12217: 'The real fastmos: C++ monstermos port' by Putnam3145 at commit 86afd889f1

## Reproduction:
Become a nightmare and try hitting lights/APCs with lighteater.

- Lights take 1 - 3 hits to break
- APCs take 2 soft stamcrits (from solely swinging lighteater) and a couple more hits to break

**Comment by Trilbyspaceclone** [comment]
Were you in combat mode?

**Comment by ghost** [comment]
> 
> 
> Were you in combat mode?

No, combat mode doesn't increase damage to objects. Nor was I ever in combat mode prior, when lights were 1-hit and APCs took roughly 16 hits, from full health, to be broken with light eater

**Comment by Ghommie** [comment]
Well, it now requires combat mode, probably one change I did for consistency instead of leaving combat mode micro managing limited to mob vs mob combat.

Yea, it throws older players off but also makes the whole stamina thing matter more for objects, though it can be minimized by toggling in on/off when necessary, so it's not that bad (except some have hard damage thresholds, which can lead to idiots bashing things out to no avail for a minute or two, but kinda shows how people can be stupid at times, which is fun)

...though someone had the funny idea of making a rest hotkey placing right beside the combat mode one a while ago, so be careful not to press that one by accident like I clumsily do until rebindable hotkeys are merged, it's pretty embarassing. Overall it can be made milder later idk.

**Comment by Arturlang** [comment]
Really should mae this kind of thing more clear, thought the same until this
