### ISSUE TITLE
Cloning utterly plucked

### ISSUE THREAD

**Issue by Nayser8** [citadel-station/citadel-main#12686]
Issue reported from  Round ID: 23493 (Citadel Station)

Reporting client version: 513

I got killed, came out of cloning as "default" human (my character is a lizard) with usual cloned haircut, i couldn't understand or speak any language and was in perfect health (no brain issues). This glitch is incredibly frustrating, fix asap. Every time i spoke there would be shown a small brain icon next to my message and no one could understand me.

**Comment by Ghommie** [comment]
The language issues and brain icons are from the mob speaking gibberish due to brain damage aphasia (cough cough unupgraded cloner), while being apparently at perfect health may have been due the anosognosia trauma, but I'm not sure.

The mob coming out of the pod as a different species does sound like a bug though.

**Comment by EmeraldSundisk** [comment]
We have any updates on this?

**Comment by Arturlang** [comment]
This is fixed, was an issue caused by tgui 3.0 testmerge
