### ISSUE TITLE
Corpses's sprites stand up as if they were alive when they get cleaned with a bar of soap.

### ISSUE THREAD

**Issue by VitorGoatman** [citadel-station/citadel-main#137]
Title says it all really. You use a bar of soap to clean the body, and it stands up in a buggy way.

https://i.gyazo.com/5466c625d070495bc0932b4370185944.png

https://i.gyazo.com/644b199f5ecf3e4f78e116b5bca5bba0.png

**Comment by LetterJay** [comment]
Probably related to the sprite bug for slipping. Anytime anything that is used to update a sprite, it breaks its rotation. This seems to be something with the species system ported from here, because I tested vanilla /tg/ and it wasn't happening. But if I move all the stuff from this codebase to the newest /tg/, it started happening again.

**Comment by ghost** [comment]
I'd suggest taking a look in the slipping code at how it updates sprites and compare whatever's in there with what we changed in species.

**Comment by Poojawa** [comment]
fixed as of #189 || unable to reproduce since then.
