### ISSUE TITLE
Maint drones being unable to weld airlocks shut

### ISSUE THREAD

**Issue by ghost** [citadel-station/citadel-main#1671]
The title. It comes from needing to have a non-help intent when using welding tool on airlock. Maint drones can't switch intents, so they can't weld airlocks shut.

**Comment by chesse20** [comment]
i mean their job is to repair the station and welding airlocks shut doesnt really help that

**Comment by LetterJay** [comment]
This isn't a bug. Welding airlocks shut was changed to utilize intents and the only way to weld it shut is by switching to harm. I can't think of any valid reason for a drone to be welding an airlock shut since that would be impeding movement and therefore hindering gameplay for others which breaks the rules of playing a drone.
