### ISSUE TITLE
Cannot re-enter implanted borer after Aghosting

### ISSUE THREAD

**Issue by Raeschen** [citadel-station/citadel-main#2282]
Exactly as the title says. 

Be borer. 
Implant into someone. 
Do admin work. 
Cannot re-enter borer,

 it says; Another consciousness is in your body...It is resisting you.

**Comment by ktccd** [comment]
By implant, do you mean infest? Or do you mean the mind-control ability?

**Comment by Raeschen** [comment]
I'll be inside a host as a borer. Not with control or anything, just sat there where i can use inject chemical abilities.

I'll Aghost to do some admin stuff.

Lo and behold i cannot return to the borer body.

**Comment by deathride58** [comment]
It's likely trying to give you control of the host's brain instead of your borer when you try to toggle Aghost off.
A likely workaround would be to view variables on host > search for borer (likely in contents) > assume direct control, or manually change its ckey to your ckey.

**Comment by ktccd** [comment]
Aghosting is weird.... But yeah, forcefully taking over the borer that's in the contents of the host should work until I learn how aghosting works...

**Comment by Poojawa** [comment]
Not really a bug so much as contents code being fucky.

**Comment by Poojawa** [comment]
for the record, aghosting leaves a copy of your ckey with an @ before it, so that it doesn't appear catatonic, just braindead. 

The borer code wasn't meant for people being able to aghost out, so it's likely slapping on the host overrides to the ghost. or sommat. can't really fix since no-one's maintaining the borer code upstream anymore.
