### ISSUE TITLE
captian cant open laser gun case

### ISSUE THREAD

**Issue by chesse20** [citadel-station/citadel-main#2284]
[Note]: makes it hard to get it out and then once you do you have to break out of your office. access denied message always

**Comment by ktccd** [comment]
It's a displaycase, and I made a PR enabling it earlier.
Problem is, whenever we synch to TG, we lose it as THEY have it so only central command operatives can open it for some reason.

**Comment by ktccd** [comment]
@kevinz000 Is it possible to send a new PR of my old fix without breaking things?

**Comment by deathride58** [comment]
Being unable to open the display case without breaking it is 100% intentional due to balance and lore.
From a gameplay perspective, the captain's laser gun is *pretty* powerful compared to most of the weapons in the armory. To allow the captain to grab the laser gun without a single bit of effort would be allowing the captain and HoP to powergame a lot easier. The captain's gun is also a traitor objective, allowing the captain the ability to freely lug it anywhere would make the difficulty of the objective clamp to the extremes of "basically a free objective" and "basically impossible" a lot more often than it already does.
From an IC perspective, the antique laser gun is meant to be the captain's most prized decorative possession. It makes sense for the captain to request a lock with a security level that nobody on station has the ability to open. There's no reason to use antique technology outside of emergencies, especially considering the station's equipped with an armory containing enough weapons to safely deal with most threats.

**Comment by ktccd** [comment]
You have a point. Setting it to centcomm-only means that he can be sure that even the HoP won't silently steal it.

**Comment by Poojawa** [comment]
As mentioned, this is for balance reasons.
