### ISSUE TITLE
Players enlarged with the size ray can stomp normal sized players

### ISSUE THREAD

**Issue by GlitchyCore** [citadel-station/citadel-main#352]
Pretty much what it says in the title.

**Comment by Poojawa** [comment]
if they're two steps larger, this is intended.

**Comment by TalkingCactus** [comment]
This is not how it should be, it's a bug. Punishing normal players is not acceptable.

**Comment by Poojawa** [comment]
It's not a bug, because it's balanced by the fact macro players are tremendously easier to click on, and being just north of them removes any retaliation at all.

**Comment by TalkingCactus** [comment]
How can they not retaliate? The title of this post is exactly how they retaliate, and it **DOESN'T** rely on clicking so it's even _easier_ for large players to win melee fights.

**Comment by TalkingCactus** [comment]
When the intermediate size between normal and large was added, the advantage that large players had on normal ones was very apparent and it was patched quickly to only affect players less than normal size. With size options not available for new-players, it only amplifies the fact that scientists can now powergame to get sizerays to make themselves exponentially stronger in melee for a slightly inconvenient sprite size. A large sprite means very little when players move so quickly that melee combat is almost impossible for anyone but the stomper, anyway.

**Comment by TalkingCactus** [comment]
Gimmick, fetish content should never provide an advantage to the normal game unless agreed upon through toggleable preferences and/or with an appropriate tradeoff in strength.

**Comment by TalkingCactus** [comment]
Not to mention their actual bounding box is static for pixel projectiles, so they're not even easier targets for ranged attacks.

**Comment by Poojawa** [comment]
> gimmick, fetish content.

> Implimentor of a system literally detailing out erotica to an exacting degree

ok.

in anycase, this is an easy case of adjusting size scaling ratios. You don't get a health bonus being bigger, nor can you carry more. the stomp was put in as brutal as it was because Narky code micros were literally hardcoded sizes. And micros being one step shorter were as large as the smallest size available in the server is now. which gave them an insane combat advantage because there quite literally was no counter.

To boot, Narky code's stomp was an Instant, unavoidable, hard stun. This inflicts stamina damage, and I'm pretty sure is blocked entirely with a riot shield as well. causing a pause between steps is way too huge a balance shift to even look at either.

**Comment by TalkingCactus** [comment]
There's also no combat logs and it's silent. If this isn't a bugged and imbalanced feature, I don't know what is. Sizerays and sizes in general are causing so much shit and grief recently because people are just now finding out they can be used for a significant combat advantage that can be used in the open since there's no way to notice they're being stepped on or stunned.

I just watched people being hard stunned by it in game as well, so it doesn't seem like much has changed since the last iteration.

Don't cherry pick a sentence for the parts you can exploit, either. None of the code you're hinting at has any real advantage for players.

**Comment by Poojawa** [comment]
resolved in #356
