### ISSUE TITLE
Objectives not working how they should

### ISSUE THREAD

**Issue by Slomacz** [citadel-station/citadel-main#3924]
Issue: bugged objectives, free objectives I find this kinda gamebreaking when you join all all you got is 4 free objectives with Traitors not even tring to do anything turning secret gamemode into extended. Also I know admin could assing you objectives but they are not available all the time. Fix that plz.

**Comment by deathride58** [comment]
Not necessarily a bug, but still an upstream issue, as this is due to how objectives are assigned. As the roundstart population increases, the chance of the game rolling a free objective decreases, as the game replaces objectives it determines are too easy or impossible with free objectives. This is less of an issue during highpop, as more job slots will end up being filled roundstart.

The system is indeed working as intended, but due to the high concentration of assistants and latejoiners on the server, the system is assuming the server is lowpop and is automatically balancing antag objectives around that.
