### ISSUE TITLE
All incenerators have a derpy air vent

### ISSUE THREAD

**Issue by lightcat** [citadel-station/citadel-main#5441]
Bottom right of this picture where the colorfulness is you can see an airvent but you can also see a pump pointed away and leading into a connector. I'm pretty sure thats supposed to be a vent there.
Cant inject anything into the room nor take it out by the pipeline so either the pumps are facing the wrong way or the vent is supposed to be a scrubber.
https://i.imgur.com/qS897Su.png

**Comment by deathride58** [comment]
Vents are able to be switched to siphon instead of refill during construction, and those vents are mapped with their siphon mode being the default. This is intentional behavior, and it works just fine, the "vent" sucks the gas out just fine. You can observe this behavior in action in the station's gas tanks.
