### ISSUE TITLE
Chaplain bible ignores cryosleep

### ISSUE THREAD

**Issue by Ragolution** [citadel-station/citadel-main#6043]
**Round ID**: 12174

**Desc**: As it says on the tin; a Chaplain Cryo'd and the one that joined after him had the previous player's bible instead of his own inside of his backpack. Does not effect Null Rod.

**How to reproduce**: Join round as Chaplain. Cryo. Chaplain slot is opened. New Chaplain joins. Instead of his respective bible, he gets your bible.

**Comment by Poojawa** [comment]
oof. I have no idea how to fix this. And it's likely unfix-able due to how the whole Holy/Cult bullshit is done

**Comment by cebutris** [comment]
This is because of how the religion subsystem works. Basically, when a chaplain signs on for the first time, they either add their religion prefs to the subsystem if nothing is there, or they pull from the subsytem if it IS there. This means that any chaplain that joins after that becomes part of that religion. I also read somewhere that they get a copy of the null rod variant the original chaplain chose, but I can't verify that.

It could probably be fixed by checking if the chaplain is the only chaplain when they cryo, and if so, remove the saved religion in the subsystem, but that seems like a bit of a ❄️

**Comment by improvedname** [comment]
@deathride58 not a issue its just how the religion system works
