### ISSUE TITLE
Mapping Issue: Multiple Maintenance APC Tiles Not Counting as Maint for Rad Storms

### ISSUE THREAD

**Issue by Kevak** [citadel-station/citadel-main#819]
Multiple tiles in maintenance with APC wire nodes on em do not count as maintenance to rad storms. Which can result in people getting anywhere from a small rad blast during rad storms to dying on account of not noticing due to no lights and assuming it's maintenance.

Reproduction: Trigger radstorm. Ghost. Turn on darkvision, fly around and look for APC's in maintenance that have the green rad overlay on them.

Unknown as to how easy bug is to fix. Looks like a mapping issue but I am no expert.

**Comment by TalkingCactus** [comment]
APCs rely on being inside the "area" that they control and every tile has an area. APCs, and their associated area, being in maintenance lets engineers maintain the vast majority of the power network without having all access. This bug can't be feasibly fixed without major changes to APC code. If you'd like, you can discuss this issue with /tg/station directly since we inherit our code from them.
