### ISSUE TITLE
rest button bug

### ISSUE THREAD

**Issue by SandPoot** [citadel-station/citadel-main#8224]
[Reproduction]: Rest then click resist or press b(on hotkey mode), the button will not know that you're already up and will try to get you up another time.

I want to see if you guys can make it so the button checks if you're resting or not.

**Comment by deathride58** [comment]
This is due to the way that autostand works. When autostand is enabled, then the rest button simply acts as a toggle for autostanding. The lack of autorest might be what leads to the slight confusion. If you disable autostand in the game preferences menu, then the rest button will act as a simple if-resting-then-attempt-stand;if-standing-then-attempt-rest button rather than an autostand toggle button.
