### ISSUE TITLE
Stimulum does not grant stun/sleep immunity

### ISSUE THREAD

**Issue by MSen9** [citadel-station/citadel-main#8782]

**Comment by Trilbyspaceclone** [comment]
Intended
Stim is to make you reduce stun, not stam. Tasers do a knock down, and stunbatons do the same.
If a xeno was about to neuro toxin / "Pin" you and you were stunned for a extended amount of time then that is a bug.
```/datum/reagent/stimulum
	description = "An unstable experimental gas that greatly increases the energy of those that inhale it"

/datum/reagent/stimulum/on_mob_metabolize(mob/living/L)
	..()
	ADD_TRAIT(L, TRAIT_STUNIMMUNE, id)
	ADD_TRAIT(L, TRAIT_SLEEPIMMUNE, id)

/datum/reagent/stimulum/on_mob_life(mob/living/carbon/M)
	M.adjustStaminaLoss(-2*REM, 0)
	current_cycle++
	holder.remove_reagent(id, 0.99)		//Gives time for the next tick of life().
	. = TRUE //Update status effects.
```

The sleep is a issue tho.

**Comment by Ghommie** [comment]
Tested this locally, the stimulum metabolizes faster than it could be supplied by breathing from a air tank full of stimulum. I can tell since the reagent blinks up on the mob reagents' list
every so often just to disappear deciseconds after.
If anyone is willing to fix it before I do, go compare the ratio of stimulum chem supplied by the homonymous gas with its shabby on_mob_life() override.
So disregard what Trilby said.
