### ISSUE TITLE
temporary transformation stinging a slimeperson triggers a heart attack

### ISSUE THREAD

**Issue by Sishen1542** [citadel-station/citadel-main#8987]
no heart = heart attack

## Reproduction:
transformation sting a slimeperson

**Comment by Ghommie** [comment]
@BurgerLUA.

**Comment by BurgerLUA** [comment]
Don't know what would cause this. Someone else needs to fix it.

**Comment by Ghommie** [comment]
> 
> 
> Don't know what would cause this. Someone else needs to fix it.

I could point out that's because [copy_dna()](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/194e420a1c45d4742dfe89e1fc0e3cdec6400ec3/code/datums/dna.dm#L58) completely replaces the user's species without setting up the species unlike [transfer_identity()](https://github.com/Citadel-Station-13/Citadel-Station-13/blob/194e420a1c45d4742dfe89e1fc0e3cdec6400ec3/code/datums/dna.dm#L39).

Ergo, you need to replace `copy_dna()` calls on line 1944 and 1954 of `code/modules/reagents/chemistry/reagents/other_reagents.dm` with `transfer_identity()`.

I may or may have not said something wrong, yet I'm not going to fix it for you myself.

**Comment by ghost** [comment]
someone should close this
