### ISSUE TITLE
Radiated Tile on Box Station

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9409]
Issue reported from  Round ID: 19476 (Citadel Station 13)

Reporting client version: 512

There's a maint tile on Box Station that still gets radiated despite being in maint, right below the law office APC.

![image](https://user-images.githubusercontent.com/7543955/66185387-3a825100-e64d-11e9-8441-bd5283bd00ea.png)

**Comment by EmeraldSundisk** [comment]
While I don't have a solution for this, I think I understand the root cause:
![MysterySolved](https://user-images.githubusercontent.com/51142887/66257796-3a1fae00-e752-11e9-8e57-85d97a922ab6.PNG)

Basically: that tile construes itself as being part of the law office so the APC can be placed outside of the office itself.

**Comment by Poojawa** [comment]
it's a holdover from when APCs didn't check the wall they were placed upon. this can be changed to maint without issue
