### ISSUE TITLE
Box maint rad shielding error

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#9706]
Issue reported from  Round ID: 19938 (Citadel Station 13)

Reporting client version: 512

On box station the tile in maint (174, 147, 2) with the Chapel Office APC is not weather proof and subject to radstorms

**Comment by KathrinBailey** [comment]
Hi, I found the issue.
![image](https://user-images.githubusercontent.com/53862927/68116545-feb00500-fef2-11e9-9ed5-61f33c5a8239.png)
That tile is part of the Chapel, because I have a PR for a box rework, I'm going to put fix it on part of that, so if it gets merged, then it should be fixed in that.
