### ISSUE TITLE
RPD needs to use resources like the RCD.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#9974]
I believe other servers have already adapted this.

**Comment by Ghommie** [comment]
Even if it were of a different codebase, no worries, just tell me which server(s).

**Comment by GrayRachnid** [comment]
I used an RPD as a borg on /tg/ and it used up my Metal Synthesizer so I assumed it used resources, turns out it doesn't and I was just high?

**Comment by davidchan13** [comment]
The difference between the RPD and RCD is the RCD duplicates the work you can do with metal and glass in hand.

RPD duplicated the work you can do with a pipe dispenser which doesn't require materials, it just produces power. The fix is to make RPD parts have no density until they are secured. Or move the disposal chutes to the metal crafting and RCD.
